"""Agregar columna estado tabla AUTO

Revision ID: 4dbfcba02614
Revises:
Create Date: 2026-05-25 20:43:15.122258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4dbfcba02614"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    postgresql.ENUM("activo", "desactivo", name="estado_auto").create(
        op.get_bind(), checkfirst=True
    )
    op.add_column(
        "auto",
        sa.Column(
            "estado", sa.Enum("activo", "desactivo", name="estado_auto"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auto", "estado")
    # ### end Alembic commands ###
